namespace ExpenseModel.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateCurrencies : DbMigration
    {
        public override void Up()
        {
            this.CreateIndex("dbo.ExchangeRate", "Effective", name: "IDX_ExchangeRateEffective");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AED', 2, 'United Arab Emirates Dirham', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AFN', 2, 'Afghan Afghani', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ALL', 2, 'Albanian Lek', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AMD', 2, 'Armenian Dram', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ANG', 2, 'Netherlands Antillean Guilder', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AOA', 2, 'Angolan Kwanza', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ARS', 2, 'Peso Argentine', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AUD', 2, 'Australian Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AWG', 2, 'Aruban Florin', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('AZN', 2, 'Azerbaijani Manat', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BAM', 2, 'Bosnia and Herzegovina Convertible Mark', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BBD', 2, 'Barbados Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BDT', 2, 'Bangladeshi Taka', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BGN', 2, 'Bulgarian Lev', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BHD', 3, 'Bahraini Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BIF', 0, 'Burundian Franc', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BMD', 2, 'Bermudian Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BND', 2, 'Brunei Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BOB', 2, 'Boliviano', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BOV', 2, 'Bolivian Mvdol (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BRL', 2, 'Brazilian Real', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BSD', 2, 'Bahamian Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BTN', 2, 'Bhutanese Ngultrum', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BWP', 2, 'Botswana Pula', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('BZD', 2, 'Belize Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CAD', 2, 'Canadian Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CDF', 2, 'Congolese Franc', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CHE', 2, 'WIR Euro (complementary currency)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CHF', 2, 'Swiss Franc', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CHW', 2, 'WIR Franc (complementary currency)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CLF', 0, 'Unidad de Fomento (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CLP', 0, 'Chilean Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CNY', 2, 'Renminbi (Chinese) Yuan', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('COP', 2, 'Colombian Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('COU', 2, 'Unidad de Valor Real (UVR) (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CRC', 2, 'Costa Rican Colon', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CUC', 2, 'Cuban Convertible Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CUP', 2, 'Cuban Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CVE', 0, 'Cape Verde Escudo', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('CZK', 2, 'Czech Koruna', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('DJF', 0, 'Djiboutian Franc', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('DKK', 2, 'Danish Krone', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('DOP', 2, 'Dominican Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('DZD', 2, 'Algerian Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('EGP', 2, 'Egyptian Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ERN', 2, 'Eritrean Nakfa', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ETB', 2, 'Ethiopian Birr', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('EUR', 2, 'Euro', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('FJD', 2, 'Fiji Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('FKP', 2, 'Falkland Islands Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GBP', 2, 'UK Pound Sterling', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GEL', 2, 'Georgian Lari', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GHS', 2, 'Ghanaian Cedi', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GIP', 2, 'Gibraltar Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GMD', 2, 'Gambian Dalasi', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GNF', 0, 'Guinean Franc', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GTQ', 2, 'Guatemalan Quetzal', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('GYD', 2, 'Guyanese Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('HKD', 2, 'Hong Kong Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('HNL', 2, 'Honduran Lempira', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('HTG', 2, 'Haitian Gourde', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('HUF', 2, 'Hungarian Forint', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('IDR', 2, 'Indonesian Rupiah', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ILS', 2, 'Israeli New Shekel', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('INR', 2, 'Indian Rupee', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('IQD', 3, 'Iraqi Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('IRR', 0, 'Iranian Rial', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ISK', 0, 'Icelandic Króna', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('JMD', 2, 'Jamaican Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('JOD', 3, 'Jordanian Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('JPY', 0, 'Japanese Yen', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KES', 2, 'Kenyan Shilling', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KGS', 2, 'Kyrgyzstani Som', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KHR', 2, 'Cambodian Riel', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KPW', 0, 'North Korean Won', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KRW', 0, 'South Korean Won', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KWD', 3, 'Kuwaiti Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KYD', 2, 'Cayman Islands Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('KZT', 2, 'Kazakhstani Tenge', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('LAK', 0, 'Lao Kip', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('LBP', 0, 'Lebanese Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('LKR', 2, 'Sri Lankan Rupee', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('LRD', 2, 'Liberian Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('LSL', 2, 'Lesotho Loti', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('LYD', 3, 'Libyan Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MAD', 2, 'Moroccan Dirham', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MDL', 2, 'Moldovan Leu', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MGA', 2, 'Malagasy Ariary', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MKD', 0, 'Macedonian Denar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MMK', 0, 'Myanmar Kyat', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MNT', 2, 'Mongolian Tögrög', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MOP', 2, 'Macanese Pataca', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MRO', 2, 'Mauritanian Ouguiya', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MUR', 2, 'Mauritian Rupee', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MVR', 2, 'Maldivian Rufiyaa', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MWK', 2, 'Malawian Kwacha', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MXN', 2, 'Mexican Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MXV', 2, 'Mexican Unidad de Inversion (UDI) (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MYR', 2, 'Malaysian Ringgit', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('MZN', 2, 'Mozambican Metical', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('NAD', 2, 'Namibian dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('NGN', 2, 'Nigerian Naira', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('NIO', 2, 'Nicaraguan Córdoba', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('NOK', 2, 'Norwegian Krone', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('NPR', 2, 'Nepalese Rupee', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('NZD', 2, 'New Zealand Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('OMR', 3, 'Omani Rial', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PAB', 2, 'Panamanian Balboa', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PEN', 2, 'Peruvian Sol', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PGK', 2, 'Papua New Guinean Kina', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PHP', 2, 'Philippine Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PKR', 2, 'Pakistani Rupee', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PLN', 2, 'Polish Złoty', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('PYG', 0, 'Paraguayan Guaraní', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('QAR', 2, 'Qatari Riyal', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('RON', 2, 'Romanian Leu', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('RSD', 2, 'Serbian Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('RUB', 2, 'Russian Ruble', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('RWF', 0, 'Rwandan Franc', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SAR', 2, 'Saudi Riyal', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SBD', 2, 'Solomon Islands Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SCR', 2, 'Seychelles Rupee', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SDG', 2, 'Sudanese Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SEK', 2, 'Swedish Krona/Kronor', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SGD', 2, 'Singapore Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SHP', 2, 'Saint Helena Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SLL', 0, 'Sierra Leonean Leone', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SOS', 2, 'Somali Shilling', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SRD', 2, 'Surinamese Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SSP', 2, 'South Sudanese Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('STN', 0, 'São Tomé and Príncipe Dobra', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SVC', 2, 'Salvadoran Colón', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SYP', 2, 'Syrian Pound', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('SZL', 2, 'Swazi Lilangeni', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('THB', 2, 'Thai Baht', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TJS', 2, 'Tajikistani Somoni', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TMT', 2, 'Turkmenistan Manat', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TND', 3, 'Tunisian Dinar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TOP', 2, 'Tongan Paʻanga', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TRY', 2, 'Turkish Lira', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TTD', 2, 'Trinidad and Tobago Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TWD', 2, 'New Taiwan Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('TZS', 2, 'Tanzanian Shilling', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('UAH', 2, 'Ukrainian Hryvnia', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('UGX', 2, 'Ugandan Shilling', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('USD', 2, 'United States Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('USN', 2, 'United States Dollar (next day) (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('USS', 2, 'United States Dollar (same day) (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('UYI', 0, 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('UYU', 2, 'Uruguayan Peso', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('UYW', 4, 'Unidad Previsional', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('UZS', 2, 'Uzbekistan Som', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('VES', 2, 'Venezuelan Bolívar Soberano', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('VND', 0, 'Vietnamese Dồng', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('VUV', 0, 'Vanuatu Vatu', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('WST', 2, 'Samoan Tala', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XAF', 0, 'CFA Franc BEAC', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XAG', 0, 'Silver (one troy ounce)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XAU', 0, 'Gold (one troy ounce)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XBA', 0, 'European Composite Unit (EURCO) (bond market unit)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XBB', 0, 'European Monetary Unit (E.M.U.-6) (bond market unit)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XBC', 0, 'European Unit of Account 9 (E.U.A.-9) (bond market unit)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XBD', 0, 'European Unit of Account 17 (E.U.A.-17) (bond market unit)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XDR', 0, 'Special drawing rights International Monetary Fund', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XPD', 0, 'Palladium (one troy ounce)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XPT', 0, 'Platinum (one troy ounce)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XSU', 0, 'SUCRE Unified System for Regional Compensation (SUCRE)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XTS', 0, 'Code reserved for testing purposes', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XUA', 0, 'ADB Unit of Account African Development Bank', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XXX', 0, 'No currency', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XCD', 2, 'East Caribbean Dollar', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XOF', 0, 'CFA Franc BCEAO', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('XPF', 0, 'CFP Franc (Franc Pacifique)', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('YER', 2, 'Yemeni Rial', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ZAR', 2, 'South African Rand', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
            this.Sql("INSERT INTO ISO4217Currency(Id, Exponent, [Name], WithdrawalDate, Active, Created, CreatedBy) VALUES('ZMW', 2, 'Zambian Kwacha', null, 1, '" + DateTime.Now + "', 'SysAdmin');");
        }

        public override void Down()
        {
            this.DropIndex("dbo.ExchangeRate", "IDX_ExchangeRateEffective");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AED';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AFN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ALL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AMD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ANG';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AOA';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ARS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AUD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AWG';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'AZN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BAM';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BBD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BDT';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BGN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BHD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BIF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BMD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BND';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BOB';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BOV';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BRL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BSD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BTN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BWP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'BZD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CAD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CDF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CHE';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CHF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CHW';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CLF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CLP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CNY';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'COP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'COU';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CRC';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CUC';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CUP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CVE';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'CZK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'DJF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'DKK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'DOP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'DZD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'EGP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ERN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ETB';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'EUR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'FJD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'FKP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GBP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GEL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GHS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GIP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GMD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GNF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GTQ';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'GYD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'HKD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'HNL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'HTG';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'HUF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'IDR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ILS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'INR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'IQD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'IRR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ISK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'JMD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'JOD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'JPY';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KES';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KGS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KHR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KES';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KPW';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KRW';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KWD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KYD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'KZT';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'LAK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'LBP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'LKR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'LRD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'LSL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'LYD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MAD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MDL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MGA';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MKD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MMK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MNT';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MOP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MRO';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MUR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MVR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MWK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MXN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MXV';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MYR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'MZN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'NAD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'NGN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'NIO';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'NOK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'NPR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'NZD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'OMR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PAB';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PEN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PGK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PHP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PKR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PLN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'PYG';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'QAR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'RON';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'RSD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'RUB';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'RWF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SAR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SBD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SCR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SDG';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SEK';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SGD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SHP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SLL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SOS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SRD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SSP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'STN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SVC';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SYP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'SZL';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'THB';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TJS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TMT';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TND';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TOP';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TRY';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TTD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TWD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'TZS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'UAH';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'UGX';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'USD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'USN';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'USS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'UYI';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'UYU';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'UYW';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'UZS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'VES';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'VND';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'VUV';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'WST';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XAF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XAG';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XAU';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XBA';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XBB';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XBC';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XBD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XDR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XPD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XPT';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XSU';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XTS';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XUA';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XXX';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XCD';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XOF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'XPF';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'YER';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ZAR';");
            this.Sql("DELETE FROM ISO4217Currency WHERE Id = 'ZMW';");
        }
    }
}
