USE [master]
GO

/****** Object:  Database [ExpensesDB]    Script Date: 2018-10-17 2:39:55 PM ******/
CREATE DATABASE [ExpensesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Expenses', FILENAME = N'C:\inetpub\wwwroot\expenseMVC\uploads\Expenses.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [FileStreamFS] CONTAINS FILESTREAM  DEFAULT
( NAME = N'FSgr', FILENAME = N'C:\inetpub\wwwroot\expenseMVC\uploads\fs1' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'ExpensesLog', FILENAME = N'C:\inetpub\wwwroot\expenseMVC\uploads\Expenses.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ExpensesDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExpensesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExpensesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExpensesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExpensesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExpensesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExpensesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExpensesDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ExpensesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExpensesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExpensesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExpensesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExpensesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExpensesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExpensesDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [ExpensesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExpensesDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ExpensesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExpensesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExpensesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExpensesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExpensesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExpensesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExpensesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExpensesDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ExpensesDB] SET  MULTI_USER 
GO

ALTER DATABASE [ExpensesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExpensesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExpensesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = READ_ONLY, DIRECTORY_NAME = N'FILESTREAM' ) 
GO

ALTER DATABASE [ExpensesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ExpensesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ExpensesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ExpensesDB] SET  READ_WRITE 
GO

USE [ExpensesDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;
GO
